"""Run and verify every reviewer-facing example with one cross-platform command."""

from __future__ import annotations

import argparse
import json

# Commands use fixed argv, no shell, and the active interpreter.
import subprocess  # nosec B404
import sys
from collections.abc import Sequence
from pathlib import Path
from typing import Any, Final

ROOT: Final = Path(__file__).resolve().parents[1]
DATASETS: Final = (
    (
        "realistic-controls",
        ROOT / "examples" / "campaign.json",
        ROOT / "examples" / "donors.jsonl",
        ROOT / "examples" / "results.jsonl",
    ),
    (
        "jll-supplied-table",
        ROOT / "examples" / "jll-supplied" / "campaign.json",
        ROOT / "examples" / "jll-supplied" / "donors.jsonl",
        ROOT / "examples" / "jll-supplied" / "results.jsonl",
    ),
)


def _run(command: list[str]) -> subprocess.CompletedProcess[str]:
    # Every command is a fixed list built in this module.
    return subprocess.run(  # nosec B603
        command,
        cwd=ROOT,
        check=False,
        capture_output=True,
        text=True,
    )


def _fixture_check() -> dict[str, Any]:
    completed = _run([sys.executable, str(ROOT / "scripts" / "build_jll_fixture.py"), "--check"])
    if completed.returncode != 0:
        raise RuntimeError(completed.stderr.strip() or "JLL fixture verification failed")
    return dict(json.loads(completed.stdout))


def _run_dataset(
    name: str,
    campaign: Path,
    donors: Path,
    expected: Path,
    output_dir: Path,
) -> dict[str, Any]:
    output = output_dir / f"{name}.results.jsonl"
    completed = _run(
        [
            sys.executable,
            "-m",
            "charity_donor_outreach",
            "generate",
            "--campaign",
            str(campaign),
            "--donors",
            str(donors),
            "--output",
            str(output),
        ]
    )
    if completed.returncode != 0:
        raise RuntimeError(completed.stderr.strip() or f"{name} execution failed")
    if output.read_bytes() != expected.read_bytes():
        raise RuntimeError(f"{name} output does not match the committed golden result")
    summary = dict(json.loads(completed.stdout))
    return {
        "name": name,
        "golden_match": True,
        "output": str(output.relative_to(ROOT)).replace("\\", "/")
        if output.is_relative_to(ROOT)
        else str(output),
        **summary,
    }


def _representative_draft(output: Path) -> tuple[str, str, str, str]:
    for line in output.read_text(encoding="utf-8").splitlines():
        record = json.loads(line)
        if not isinstance(record, dict) or not isinstance(record.get("draft"), dict):
            continue
        draft = record["draft"]
        donor_id = record.get("donor_id")
        status = record.get("status")
        subject = draft.get("subject_line")
        body = draft.get("body")
        if (
            isinstance(donor_id, str)
            and isinstance(status, str)
            and isinstance(subject, str)
            and isinstance(body, str)
        ):
            return donor_id, status, subject, body
    raise RuntimeError(f"{output.name} has no representative draft")


def _write_reviewer_summary(output_dir: Path, datasets: list[dict[str, Any]]) -> Path:
    summary_path = output_dir / "reviewer-summary.md"
    lines = [
        "# Reviewer demo results",
        "",
        "Both datasets were regenerated by the committed implementation and matched their "
        "golden outputs.",
        "No outreach was sent.",
        "",
        "| Dataset | Records | Statuses | Golden match |",
        "| --- | ---: | --- | :---: |",
    ]
    for dataset in datasets:
        statuses = dataset["statuses"]
        if not isinstance(statuses, dict):
            raise RuntimeError(f"{dataset['name']} returned invalid status counts")
        status_text = ", ".join(f"{key}: {value}" for key, value in sorted(statuses.items()))
        lines.append(
            f"| {dataset['name']} | {dataset['records']} | {status_text} | "
            f"{'yes' if dataset['golden_match'] else 'no'} |"
        )

    for dataset in datasets:
        output = output_dir / f"{dataset['name']}.results.jsonl"
        donor_id, status, subject, body = _representative_draft(output)
        lines.extend(
            [
                "",
                f"## {dataset['name']}: representative draft",
                "",
                f"Donor `{donor_id}` · status `{status}` · subject `{subject}`",
                "",
                "```text",
                body,
                "```",
            ]
        )
    lines.extend(
        [
            "",
            "`draft_ready` means the draft passed automated checks; it does not mean approved "
            "or sent.",
        ]
    )
    summary_path.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    return summary_path


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=ROOT / "out" / "reviewer-demo",
        help="Directory for regenerated result files (default: out/reviewer-demo).",
    )
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    output_dir = args.output_dir if args.output_dir.is_absolute() else ROOT / args.output_dir
    try:
        fixture = _fixture_check()
        datasets = [
            _run_dataset(name, campaign, donors, expected, output_dir)
            for name, campaign, donors, expected in DATASETS
        ]
        reviewer_summary = _write_reviewer_summary(output_dir, datasets)
    except (OSError, UnicodeError, json.JSONDecodeError, RuntimeError) as error:
        print(str(error), file=sys.stderr)
        return 2
    summary_display = (
        str(reviewer_summary.relative_to(ROOT)).replace("\\", "/")
        if reviewer_summary.is_relative_to(ROOT)
        else str(reviewer_summary)
    )
    print(
        json.dumps(
            {"fixture": fixture, "datasets": datasets, "reviewer_summary": summary_display},
            indent=2,
            sort_keys=True,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
